WenjieDu/PyPOTS

- pypots/classification/raindrop.py
- pypots/imputation/base.py
- pypots/imputation/locf.py
> fix: brits imputation test device mismatch

- .github/workflows/publish_to_PyPI.yml
Add a workflow to automatically publish the package to PyPI when creating a new release.
> feat: add workflow Publish-to-PyPI

- .github/workflows/testing.yml
- .github/workflows/testing_daily.yml
- README.md
- pypots/imputation/base.py
- pypots/imputation/brits.py
- pypots/imputation/saits.py
- pypots/imputation/transformer.py
- pypots/tests/test_data.py
- pypots/tests/test_environment_conda.yml
- pypots/tests/test_environment_pip.txt
- pypots/tests/test_imputation.py
- pypots/tests/unified_data_for_test.py
In this PR, I simplified the input of `pypots.imputation.base.base.py()` by removing arguments `val_X_intact` and `val_indicating_mask`. The two removed data arguments should be included in the input `val_set`of `fit()` in imputation models, namely, there should be `X_intact` and `indicating_mask` in the `val_set` no matter it is a dictionary or an HDF5 file.
Minorly, in this PR, I also added a daily testing workflow to regularly run all test cases with environment dependencies managed by `pip` rather than `conda`.
> Make imputation models `val_X_intact` and `val_indicating_mask` be included in input `val_set` originally

- .github/workflows/testing.yml
- .github/workflows/testing_daily.yml
- pypots/base.py
- pypots/classification/base.py
- pypots/classification/brits.py
- pypots/classification/raindrop.py
- pypots/clustering/base.py
- pypots/clustering/crli.py
- pypots/clustering/vader.py
- pypots/forecasting/base.py
- pypots/imputation/base.py
- pypots/imputation/brits.py
- pypots/imputation/saits.py
- pypots/imputation/transformer.py
- pypots/tests/environment_for_pip_test.txt
- pypots/tests/global_test_config.py
- pypots/tests/test_classification.py
- pypots/tests/test_clustering.py
- pypots/tests/test_data.py
- pypots/tests/test_imputation.py
- pypots/tests/test_utils.py
I add implementations for each task and model to help save training logs into tensorboard files. Test cases to validate saving files are also added.
> Save training logs into tensorboard files

- pypots/utils/commands/base.py
- pypots/utils/commands/dev.py
- pypots/utils/commands/doc.py
- pypots/utils/commands/env.py
- pypots/utils/commands/pypots_cli.py
This PR is to add the feature requested in [PyPOTS needs a tool like pypots-cli env. wenjiedu/pypots#65](https://github.com/wenjiedu/pypots/issues/65)
> Add `pypots-cli dev`

- .github/workflows/testing.yml
- pypots/tests/test_cli.py
This PR is to fix previous bugs the testing cases in `test_cli.py` that are 
1. deleting `.coverage` file causes the mis-calculation of the code coverage;
2. linting code with Black reformats the code and results in discrepancy between records in the `.coverage` file and actual code;
Both fixed in this PR.
> Fix bugs in the code-coverage report

- .github/workflows/testing_daily.yml
- setup.cfg
- setup.py
In this PR, I removed the version limitations on numpy and sklearn, and installed the dependencies in the scope of `dev` for the workflow `DailyTesting`.
> Fix dependency error in daily testing

- README.md
- docs/conf.py
- docs/index.rst
- docs/pypots.utils.rst
- docs/references.rst
- environment-dev.yml
- setup.cfg
Fix the footer issue #80 on the docs home page, and update the docs.
> Fix the footer issue on the docs home page, and update the docs

- .github/workflows/greetings.yml
- .readthedocs.yaml
- docs/index.rst
- environment-dev.yml
- pypots/base.py
- pypots/classification/base.py
- pypots/classification/brits.py
- pypots/classification/grud.py
- pypots/classification/raindrop.py
- pypots/clustering/base.py
- pypots/clustering/crli.py
- pypots/clustering/vader.py
- pypots/forecasting/base.py
- pypots/imputation/base.py
- pypots/imputation/brits.py
- pypots/imputation/saits.py
- pypots/imputation/transformer.py
- pypots/tests/global_test_config.py
- pypots/tests/test_classification.py
- pypots/tests/test_clustering.py
- pypots/tests/test_imputation.py
- setup.cfg
1. add argument `model_saving_strategy` for all models to enable different model saving strategies;
2. update test cases, test loading the saved model;
> Enable different model saving strategies with argument `model_saving_strategy`

- docs/about_us.rst
- docs/conf.py
Fixes #97, and add Maciej into the development team.
> Fix not shown heading `Attributes` in docs, and update the docs

- .github/workflows/testing_daily.yml
* Fixes #100 , which is for daily-testing workflow, not including ci-testing workflow;
> Should use package `pypots` as the source for code coverage calculation, rather than `tests`

- .github/ISSUE_TEMPLATE/config.yml
- .readthedocs.yaml
- README.md
- docs/index.rst
- update docs;
- fix #102, and build successfully in this build https://readthedocs.org/projects/pypots/builds/20606148/;
> Update docs, and fix the misdisplayed footer on the page `References`

- .coveragerc
- .github/workflows/testing_ci.yml
Add `.coveragerc` to omit files in templates from coverage calculation.
> Add `.coveragerc` to omit files in templates

- .github/workflows/publish_to_PyPI.yml
* fix: use setup instead of build;
To fix the error returned by PyPI website:
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/ Only one sdist may be uploaded per release.
> Use `setup` instead of `build` to build release

- tests/test_training_on_multi_gpus.py
Fixes #123  (issue)
If tests are run with a brutal global `pytest`, they fail if the host machine has less than two cuda-enabled devices. This is almost expected, since we want to test multi-gpu behaviour, but this makes local development difficult on laptops or zero/single gpu machines.
I propose skipping the module alltogether if the machine has less than two cuda-enabled devices.
As a bonus, I disable the upper cap of 2 cuda devices - let's test all of them!
> skip multi-gpu test if not multi-gpu host

- docs/examples.rst
- pypots/base.py
- pypots/utils/random.py
Fix #130, and update som logging info.
> Update logging, and fix the error in the usage example 

- pypots/base.py
I noticed that if I pass a list containing a single item as `device` to any model that derives from `BaseModel` it results in an AssertionError, which I think is erroneous.
`AssertionError: The list of devices should have at least 1 device, but got 0.`
I test if the `device` variable is one item long. If it is, I extract the object it contains and rerun `self._setup_device` recursively.
> Fix single-item device list throwing an error

- .github/workflows/testing_ci.yml
- README.md
- docs/about_us.rst
- docs/faq.rst
- docs/index.rst
- docs/milestones.rst
- pypots/classification/raindrop/model.py
- pypots/classification/raindrop/modules.py
> Fixing the bug in raindrop when running on multiple devices

- pypots/data/utils.py
Fix the type hint for function `mcar()` in comments
the `mcar()` function should return 4 values: (`X_intact`, `X`, `missing_mask`, `indicating_mask`) rather than the only `X`
> fix: the type hint for function `mcar()` in comments

- docs/faq.rst
- pypots/__init__.py
1. updating the FAQ page in docs;
2. releasing v0.1.2;
> Updating docs and releasing v0.1.2

- pypots/imputation/saits/model.py
- pypots/imputation/transformer/model.py
- pypots/modules/self_attention.py
> feat: add Transformer encoder, decoder, and decoder_layer;

- pypots/clustering/crli/model.py
- pypots/clustering/vader/model.py
- tests/clustering/crli.py
- tests/clustering/vader.py
> Extract latent from clustering models

- docs/pypots.optim.rst
- pypots/optim/adadelta.py
- pypots/optim/adagrad.py
- pypots/optim/adam.py
- pypots/optim/adamw.py
- pypots/optim/base.py
- pypots/optim/lr_scheduler/__init__.py
- pypots/optim/lr_scheduler/base.py
- pypots/optim/lr_scheduler/constant_lrs.py
- pypots/optim/lr_scheduler/exponential_lrs.py
- pypots/optim/lr_scheduler/lambda_lrs.py
- pypots/optim/lr_scheduler/linear_lrs.py
- pypots/optim/lr_scheduler/multiplicative_lrs.py
- pypots/optim/lr_scheduler/multistep_lrs.py
- pypots/optim/lr_scheduler/step_lrs.py
- pypots/optim/rmsprop.py
- pypots/optim/sgd.py
- tests/optim/lr_schedulers.py
> Add learning-rate schedulers

- .github/workflows/testing_ci.yml
- setup.cfg
> Fixing failed CI testing due to dependency installation error

- pypots/imputation/__init__.py
- pypots/imputation/csdi/__init__.py
- pypots/imputation/csdi/data.py
- pypots/imputation/csdi/model.py
- pypots/imputation/csdi/modules/__init__.py
- pypots/imputation/csdi/modules/core.py
- pypots/imputation/csdi/modules/submodules.py
- tests/imputation/csdi.py
> Adding the model CSDI 

- README.md
- docs/pypots.imputation.rst
- docs/pypots.modules.rst
- docs/pypots.rst
- docs/references.bib
- pypots/classification/grud/modules/__init__.py
- pypots/classification/grud/modules/core.py
- pypots/imputation/__init__.py
- pypots/imputation/brits/modules/core.py
- pypots/imputation/csdi/__init__.py
- pypots/imputation/csdi/data.py
- pypots/imputation/csdi/model.py
- pypots/imputation/csdi/modules/__init__.py
- pypots/imputation/csdi/modules/core.py
- pypots/imputation/csdi/modules/submodules.py
- pypots/modules/rnn.py
- pypots/modules/self_attention.py
- tests/imputation/csdi.py
1. fixing #207;
2. updating the docs;
> Adding CSDI, updating the docs

- .readthedocs.yaml
- docs/index.rst
- docs/pygrinder.rst
- docs/tsdb.rst
> Adding tsdb and pygrinder into the docs

- .readthedocs.yaml
Clone TSDB and PyGrinder before building PyPOTS docs to apply the latest code and docs from both libraries.
> Clone TSDB and PyGrinder repos to use their latest code and docs

- README.md
- docs/conf.py
- docs/index.rst
- pypots/classification/base.py
- pypots/cli/tuning.py
- pypots/clustering/base.py
- pypots/clustering/crli/model.py
- pypots/clustering/vader/model.py
- pypots/forecasting/base.py
- pypots/imputation/base.py
- pypots/imputation/brits/model.py
- pypots/imputation/csdi/model.py
- pypots/imputation/gpvae/model.py
- pypots/imputation/mrnn/model.py
- pypots/imputation/saits/model.py
- pypots/imputation/transformer/model.py
- pypots/imputation/usgan/model.py
1. fixing #232;
2. fixing #233;
3. updating docs;
> Check if X_intact contains missing data for imputation models, check and list mismatched hyperparameters in the tuning mode

- pypots/imputation/locf/model.py
- tests/imputation/locf.py
> Adding other options for the first step imputation in LOCF

- .github/workflows/testing_ci.yml
- README.md
- docs/faq.rst
- docs/index.rst
- docs/install.rst
> Testing with Python 3.11 and support it

- pypots/base.py
- tests/classification/brits.py
- tests/classification/grud.py
- tests/classification/raindrop.py
- tests/clustering/crli.py
- tests/clustering/vader.py
- tests/imputation/brits.py
- tests/imputation/csdi.py
- tests/imputation/gpvae.py
- tests/imputation/mrnn.py
- tests/imputation/saits.py
- tests/imputation/transformer.py
- tests/imputation/usgan.py
Replace save_model() and load_model() with save() and load(). Old functions save_model() and load_model() are still kept for compatibility and will be removed in the future.
> Rename save_model() and load_model() into save() and load()

- docs/references.bib
- pypots/imputation/__init__.py
- pypots/imputation/timesnet/__init__.py
- pypots/imputation/timesnet/data.py
- pypots/imputation/timesnet/model.py
- pypots/imputation/timesnet/modules/__init__.py
- pypots/imputation/timesnet/modules/core.py
- pypots/imputation/timesnet/modules/embedding.py
- pypots/imputation/timesnet/modules/layer.py
- tests/imputation/timesnet.py
> Adding TimesNet as an imputation model

- pypots/imputation/csdi/data.py
- pypots/imputation/csdi/model.py
- pypots/imputation/csdi/modules/core.py
> Making CSDI val process same as the original

- pypots/imputation/transformer/model.py
Add back the missing argument attn_dropout.
> Fix missing argument attn_dropout in imputation Transformer

- pypots/utils/metrics/error.py
Adding a unified func _check_inputs() to help check inputs' values and shapes for error calculation functions.
> Adding _check_inputs() for error calculation functions

- pypots/classification/base.py
- pypots/clustering/base.py
- pypots/clustering/crli/model.py
- pypots/clustering/vader/model.py
- pypots/forecasting/base.py
- pypots/imputation/base.py
- pypots/imputation/csdi/data.py
- pypots/imputation/csdi/model.py
- pypots/imputation/csdi/modules/core.py
- pypots/imputation/csdi/modules/submodules.py
- pypots/imputation/gpvae/model.py
- pypots/imputation/usgan/model.py
1. fix the bug that val_set didn't return X_ori in CSDI;
2. add 0s placeholder for epoch number in logging;
3. ensure n_sampling_times>0 for CSDI and GP-VAE predict();
> Fixing CSDI, adding placeholder for epoch num in logging

- pypots/base.py
- pypots/cli/tuning.py
- pypots/imputation/locf/model.py
- tests/global_test_config.py
- tests/imputation/locf.py
…first_step_imputation;
Fixing #281
> Fixing the infinite loop in LOCF

- pypots/data/utils.py
- pypots/imputation/mrnn/data.py
Fix the problem mentioned in the issue #294.
> Fixing the issue in delta calculation

- pypots/utils/visual/data.py
> Remind how to display the figs rather than invoking plt.show()

- README.md
- docs/index.rst
- docs/install.rst
- docs/milestones.rst
- pypots/base.py
- pypots/classification/base.py
- pypots/clustering/base.py
- pypots/clustering/crli/model.py
- pypots/clustering/vader/model.py
- pypots/forecasting/base.py
- pypots/imputation/base.py
- pypots/imputation/csdi/model.py
- pypots/imputation/gpvae/model.py
- pypots/imputation/usgan/model.py
1. removed the deprecated save_model() and load_model();
2. updated the docs;
> Removing deprecated functions

- pypots/nn/modules/transformer/attention.py
- pypots/nn/modules/transformer/layers.py
Refactor and simplify MHA, put dropout, layernorm, and residual connection into EncoderLayer.
> Simplify MultiHeadAttention

- pypots/imputation/__init__.py
- pypots/imputation/autoformer/data.py
- pypots/imputation/autoformer/model.py
- pypots/imputation/autoformer/modules/core.py
- pypots/imputation/patchtst/__init__.py
- pypots/imputation/patchtst/data.py
- pypots/imputation/patchtst/model.py
- pypots/imputation/patchtst/modules/__init__.py
- pypots/imputation/patchtst/modules/core.py
- pypots/imputation/patchtst/modules/submodules.py
- tests/imputation/autoformer.py
- tests/imputation/patchtst.py
1. add PatchTST as an imputation method, as suggested in #295;
> Adding PatchTST as an imputation model

- pypots/imputation/__init__.py
- pypots/imputation/autoformer/model.py
- pypots/imputation/dlinear/__init__.py
- pypots/imputation/dlinear/data.py
- pypots/imputation/dlinear/model.py
- pypots/imputation/dlinear/modules/__init__.py
- pypots/imputation/dlinear/modules/core.py
- pypots/imputation/patchtst/model.py
- pypots/imputation/timesnet/model.py
- tests/imputation/dlinear.py
1. add DLinear as an imputation model, as suggested in #295;
> Add DLinear as an imputation model

- environment-dev.yml
- pypots/imputation/__init__.py
- pypots/imputation/etsformer/__init__.py
- pypots/imputation/etsformer/data.py
- pypots/imputation/etsformer/model.py
- pypots/imputation/etsformer/modules/__init__.py
- pypots/imputation/etsformer/modules/core.py
- pypots/imputation/etsformer/modules/submodules.py
- requirements.txt
- setup.cfg
- setup.py
- tests/environment_for_conda_test.yml
- tests/imputation/etsformer.py
1. add ETSformer as an imputation model, as suggested in #295;
> Add ETSformer as an imputation model

- pypots/imputation/__init__.py
- pypots/imputation/crossformer/__init__.py
- pypots/imputation/crossformer/data.py
- pypots/imputation/crossformer/model.py
- pypots/imputation/crossformer/modules/__init__.py
- pypots/imputation/crossformer/modules/core.py
- pypots/imputation/crossformer/modules/submodules.py
- tests/imputation/crossformer.py
1. add Crossformer as an imputation model, as suggested in #295;
> Add Crossformer as an imputation model

- environment-dev.yml
- pypots/imputation/__init__.py
- pypots/imputation/fedformer/__init__.py
- pypots/imputation/fedformer/data.py
- pypots/imputation/fedformer/model.py
- pypots/imputation/fedformer/modules/__init__.py
- pypots/imputation/fedformer/modules/core.py
- pypots/imputation/fedformer/modules/submodules.py
- requirements.txt
- setup.cfg
- setup.py
- tests/environment_for_conda_test.yml
- tests/imputation/fedformer.py
1. add FEDformer as an imputation model, as suggested in #295;
> Add FEDformer as an imputation model

- README.md
- docs/index.rst
- docs/pypots.imputation.rst
- docs/references.bib
- pypots/imputation/__init__.py
- pypots/imputation/autoformer/modules/core.py
- pypots/imputation/autoformer/modules/submodules.py
- pypots/imputation/fedformer/modules/core.py
- pypots/imputation/informer/__init__.py
- pypots/imputation/informer/data.py
- pypots/imputation/informer/model.py
- pypots/imputation/informer/modules/__init__.py
- pypots/imputation/informer/modules/core.py
- pypots/imputation/informer/modules/submodules.py
- tests/imputation/informer.py
1. add Informer as an imputation method, as suggested in #295;
> Add informer as an imputation model

- pypots/base.py
- pypots/classification/base.py
- pypots/clustering/base.py
- pypots/clustering/crli/model.py
- pypots/clustering/vader/model.py
- pypots/forecasting/base.py
- pypots/imputation/base.py
- pypots/imputation/csdi/model.py
- pypots/imputation/gpvae/model.py
- pypots/imputation/usgan/model.py
> Add the attribute `best_epoch` to record the best epoch num

- README.md
- pypots/__init__.py
- pypots/imputation/autoformer/modules/core.py
- pypots/imputation/crossformer/modules/core.py
- pypots/imputation/crossformer/modules/submodules.py
- pypots/imputation/dlinear/model.py
- pypots/imputation/dlinear/modules/core.py
- pypots/imputation/etsformer/modules/core.py
- pypots/imputation/fedformer/modules/core.py
- pypots/imputation/informer/__init__.py
- pypots/imputation/informer/modules/core.py
- pypots/imputation/patchtst/modules/core.py
- pypots/nn/modules/transformer/attention.py
- tests/imputation/dlinear.py
1. apply SAITS embedding strategy to the newly added models as we discussed in #295;
2. update README;
3. release v0.4;
> Release v0.4, apply SAITS embedding strategy to the newly added models, and update README

- pypots/imputation/autoformer/model.py
- pypots/imputation/autoformer/modules/core.py
- pypots/imputation/autoformer/modules/submodules.py
- pypots/imputation/crossformer/model.py
- pypots/imputation/crossformer/modules/core.py
- pypots/imputation/dlinear/model.py
- pypots/imputation/dlinear/modules/core.py
- pypots/imputation/etsformer/model.py
- pypots/imputation/etsformer/modules/core.py
- pypots/imputation/fedformer/model.py
- pypots/imputation/fedformer/modules/core.py
- pypots/imputation/informer/model.py
- pypots/imputation/informer/modules/core.py
- pypots/imputation/informer/modules/submodules.py
- pypots/imputation/patchtst/model.py
- pypots/imputation/patchtst/modules/core.py
1. apply both ORT and MIT loss from SAITS paper to newly added models (Crossformer, PatchTST, DLinear, ETSformer, FEDformer, Informer, and Autoformer), and add loss weight arguments to balance them. Previously, the seven models are trained only with MIT loss;
> Apply SAITS loss to new models

- .github/workflows/testing_ci.yml
- pypots/nn/modules/raindrop/__init__.py
1. fixing #352;
2. in previous commits, we expose ObservationPropagation in the below line, but this will cause the exception`name 'MessagePassing' is not defined` if torch_geometric is not installed. We remove this line in this PR to fix this issue. https://github.com/WenjieDu/PyPOTS/blob/aecd14b331a70c52f9174064b28ddf91445832ce/pypots/nn/modules/raindrop/__init__.py#L16
> Avoid the import error `MessagePassing not defined`

- docs/pypots.imputation.rst
- docs/references.bib
- pypots/imputation/__init__.py
- pypots/imputation/frets/__init__.py
- pypots/imputation/frets/core.py
- pypots/imputation/frets/data.py
- pypots/imputation/frets/model.py
- pypots/nn/modules/frets/__init__.py
- pypots/nn/modules/frets/backbone.py
- tests/imputation/frets.py
> Implement FreTS as an imputation model 

- docs/pypots.imputation.rst
- docs/references.bib
- pypots/imputation/__init__.py
- pypots/imputation/itransformer/__init__.py
- pypots/imputation/itransformer/core.py
- pypots/imputation/itransformer/data.py
- pypots/imputation/itransformer/model.py
- tests/imputation/itransformer.py
> Implement iTransformer as an imputation model

- pypots/data/generating.py
1. train_X_ori and val_X_ori didn't get standardized, fix in this PR;
> Fix error in gene_random_walk

- pypots/nn/modules/raindrop/backbone.py
- pypots/nn/modules/raindrop/layers.py
> Try to import torch_geometric only when init Raindrop

- pypots/imputation/__init__.py
- pypots/imputation/pyraformer/__init__.py
- pypots/imputation/pyraformer/core.py
- pypots/imputation/pyraformer/data.py
- pypots/imputation/pyraformer/model.py
- pypots/imputation/transformer/model.py
- pypots/nn/modules/pyraformer/__init__.py
- pypots/nn/modules/pyraformer/autoencoder.py
- pypots/nn/modules/pyraformer/layers.py
- tests/imputation/pyraformer.py
> Implement Pyraformer as an imputation model

- pypots/imputation/__init__.py
- pypots/imputation/scinet/__init__.py
- pypots/imputation/scinet/core.py
- pypots/imputation/scinet/data.py
- pypots/imputation/scinet/model.py
- pypots/nn/modules/scinet/__init__.py
- pypots/nn/modules/scinet/backbone.py
- pypots/nn/modules/scinet/layers.py
- tests/global_test_config.py
- tests/imputation/scinet.py
> Add SCINet modules and implement it as an imputation model

- pypots/imputation/__init__.py
- pypots/imputation/micn/__init__.py
- pypots/imputation/micn/core.py
- pypots/imputation/micn/data.py
- pypots/imputation/micn/model.py
- pypots/nn/modules/fedformer/layers.py
- pypots/nn/modules/micn/__init__.py
- pypots/nn/modules/micn/backbone.py
- pypots/nn/modules/micn/layers.py
- tests/imputation/micn.py
> Add MICN modules and implement it as an imputation model

- pypots/imputation/__init__.py
- pypots/imputation/tide/__init__.py
- pypots/imputation/tide/core.py
- pypots/imputation/tide/data.py
- pypots/imputation/tide/model.py
- pypots/nn/modules/tide/__init__.py
- pypots/nn/modules/tide/autoencoder.py
- pypots/nn/modules/tide/layers.py
- tests/imputation/tide.py
> Add TiDE modules and implement it as an imputation model 

- .github/workflows/testing_ci.yml
- pypots/nn/modules/reformer/local_attention.py
- pypots/nn/modules/reformer/lsh_attention.py
https://github.com/WenjieDu/PyPOTS/actions/runs/9561737298/job/26356597964
> Fix linting error

- pypots/imputation/timesnet/core.py
- pypots/nn/modules/transformer/embedding.py
> Make the number of max steps adjustable in TimesNet

- README.md
- README_zh.md
- docs/index.rst
- docs/references.bib
- pypots/imputation/__init__.py
- pypots/imputation/imputeformer/__init__.py
- pypots/imputation/imputeformer/core.py
- pypots/imputation/imputeformer/data.py
- pypots/imputation/imputeformer/model.py
- pypots/nn/modules/imputeformer/__init__.py
- pypots/nn/modules/imputeformer/attention.py
- pypots/nn/modules/imputeformer/mlp.py
- pypots/nn/modules/revin/layers.py
- tests/imputation/imputeformer.py
1. fixing #451;
2. fixing #453;
3. update docs;
> Add ImputeFormer, fix RevIN, and update docs

- pypots/imputation/__init__.py
- pypots/imputation/lerp/__init__.py
- pypots/imputation/lerp/model.py
- tests/imputation/lerp.py
Add linear interpolation (Lerp) imputation method as a new naive model. 
Logic is implemented directly in the model.py file, much like the format for Median/ Mean naive models. Test is implemented in tests/imputation/lerp.py, which matches the format of test files for Median/ Mean exactly. Model name is added to the imputation folder's init file.
> Implement Linear Interpolation (Lerp) Imputation Method

- docs/references.bib
- pypots/imputation/__init__.py
- pypots/imputation/tcn/__init__.py
- pypots/imputation/tcn/core.py
- pypots/imputation/tcn/data.py
- pypots/imputation/tcn/model.py
- pypots/nn/modules/tcn/__init__.py
- pypots/nn/modules/tcn/backbone.py
- pypots/nn/modules/tcn/layers.py
- tests/imputation/tcn.py
> Add TCN as an imputation model

- pypots/classification/base.py
- pypots/clustering/crli/model.py
- pypots/clustering/vader/model.py
- pypots/forecasting/base.py
- pypots/forecasting/csdi/model.py
- pypots/imputation/base.py
- pypots/imputation/csdi/model.py
- pypots/imputation/gpvae/model.py
- pypots/imputation/usgan/model.py
> Fix saving failed when the strategy is 'better'

- pypots/utils/visual/visualizeAttention.py
Added file visualizeAttention.py to pypots.utils.visual for visualization of attention matrix from DMSA heads of SAITS.
The required dependencies are: numpy, seaborn, matplotlib
Fixing #178
> Visualize attention matrix in SAITS

- pypots/data/saving/pickle.py
- pypots/nn/modules/etsformer/layers.py
- pypots/utils/visual/attention_map.py
- pypots/utils/visual/visualizeAttention.py
1. fixing #178;
2. refactoring code;
> Add attention map visualization func

- pypots/data/load_specific_datasets.py
Fixing # (issue) None
I’ve seen `load_specific_dataset` has only been added back temporarily in v0.7.1, and actually BenchPOTS will be the preferred way in the future. So this might not be too important. But got a bit confused when reading this and realized it’s been renamed from `tsdb.load_data` to `tsdb.load`.
Let me know if I have got this wrong!
Best,
> Update tsdb.load_dataset to tsdb.load in doc of load_specific_dataset

- pypots/imputation/__init__.py
- pypots/imputation/timemixer/__init__.py
- pypots/imputation/timemixer/core.py
- pypots/imputation/timemixer/data.py
- pypots/imputation/timemixer/model.py
- pypots/nn/modules/timemixer/__init__.py
- pypots/nn/modules/timemixer/backbone.py
- pypots/nn/modules/timemixer/layers.py
- tests/imputation/timemixer.py
> Implement TimeMixer as an imputation model

- pypots/base.py
> Fix unintended overwrite saving

- README.md
- README_zh.md
- docs/index.rst
The link to Reformer in README file is wrong to be Pyraformer's.
https://github.com/WenjieDu/PyPOTS/blob/467af2f7f2d5b99b3a6415fb246b74d58ac4edc0/README.md?plain=1#L480
> Fix error link to Reformer on openreview

- .gitignore
- tests/classification/csai.py
- tests/imputation/csai.py
> add csai test cases

- tests/imputation/segrnn.py
> Add SegRNN testing cases

- pypots/classification/base.py
> Fix wrong dim when concatenating eval labels in pypots.classification.base
