WenjieDu/PyPOTS

- pypots/base.py
- pypots/clustering/crli.py
- pypots/clustering/vader.py
Fix the bugs in VaDER and CRLI that tensors are on different devices when running on CUDA.
> fix the bug of tensors on different devices

- README.md
- docs/examples.rst
- docs/faq.rst
- docs/index.rst
- docs/install.rst
> Add the documentation pages of FAQ and examples

- .readthedocs.yaml
- docs/conf.py
Add the tag from google analytics to our docs.
> Add gtag to the docs site

- README.md
- docs/index.rst
Fix the corrupted testing badge in README caused by renaming the workflow.
> Fix the corrupted testing badge caused by renaming the workflow

- .github/workflows/publish_to_PyPI.yml
> Fix the failed auto release workflow with missing dependencies

- .github/workflows/publish_to_PyPI.yml
> Use `setup` instead of `build` to build release

- pypots/base.py
- pypots/classification/grud/model.py
- pypots/classification/raindrop/model.py
- pypots/clustering/crli/model.py
- pypots/clustering/vader/model.py
- pypots/clustering/vader/modules.py
- pypots/imputation/mrnn/model.py
- tests/global_test_config.py
- tests/test_forecasting.py
- tests/test_training_on_multi_gpus.py
- fix VaDER failed testing on multiple CUDA devices;
- fix MRNN failed training on multiple CUDA devices;
> Fix VaDER failed testing and MRNN failed training on multiple devices

- tests/environment_for_conda_test.yml
> Specifying the version of protobuf<=4.21.12 to fix issue #135

- CITATION.cff
- README.md
- docs/faq.rst
- docs/index.rst
Update the documentations and the citation info of PyPOTS;
> Update docs and citation info

- .github/workflows/testing_daily.yml
> Fix daily testing

- .github/workflows/testing_daily.yml
- README.md
- docs/faq.rst
- docs/index.rst
1. update docs;
2. Fixes #142 ;
> Fixing failed daily testing with MacOS python 3.7, and update docs

- .github/workflows/testing_ci.yml
- README.md
- docs/about_us.rst
- docs/faq.rst
- docs/index.rst
- docs/milestones.rst
- pypots/classification/raindrop/model.py
- pypots/classification/raindrop/modules.py
> Updating docs, and fixing the bug in raindrop when running on multiple devices

- README.md
> Fixing the invalid badge of PyPI downloads

- .github/workflows/stale.yml
- docs/examples.rst
1. update actions/stale to v8;
2. fix docs typo
> Update actions/stale@v8, and fix docs typo

- .github/workflows/greetings.yml
- docs/about_us.rst
1. fixing #158;
2. updating the docs;
> Update the greeting workflow, and update the docs

- .github/workflows/greetings.yml
- .github/workflows/stale.yml
- README.md
- docs/faq.rst
- docs/index.rst
> Updating workflows and docs

- .readthedocs.yaml
> Fixing failed doc build

- .github/workflows/testing_ci.yml
- docs/pypots.data.rst
- docs/pypots.imputation.rst
- pypots/base.py
- pypots/classification/base.py
- pypots/classification/brits/model.py
- pypots/classification/grud/model.py
- pypots/classification/raindrop/model.py
- pypots/clustering/base.py
- pypots/clustering/crli/model.py
- pypots/clustering/vader/model.py
- pypots/forecasting/base.py
- pypots/imputation/base.py
- pypots/imputation/brits/model.py
- pypots/imputation/gpvae/model.py
- pypots/imputation/mrnn/model.py
- pypots/imputation/transformer/model.py
- pypots/utils/metrics.py
1. add internal and external cluster validation functions;
2. fixing #177, enable CRLI and VaDER to return latent for advanced analysis
> Add internal and external cluster validation funcs, and enable CRLI and VaDER to return latent for advanced analysis

- README.md
- environment-dev.yml
- pypots/__init__.py
> Releasing v0.1.3;

- .readthedocs.yaml
- README.md
- docs/about_us.rst
- docs/examples.rst
- docs/index.rst
- docs/install.rst
- docs/pygrinder.rst
- docs/tsdb.rst
- environment-dev.yml
- pypots/classification/grud/data.py
- pypots/cli/env.py
- pypots/data/__init__.py
- pypots/data/generating.py
- pypots/data/utils.py
- pypots/imputation/brits/data.py
- pypots/imputation/csdi/data.py
- pypots/imputation/saits/data.py
- setup.cfg
- setup.py
- tests/environment_for_conda_test.yml
> Merge the docs of PyPOTS ecosystem, and replace pycorruptor with pygrinder in pypots

- .readthedocs.yaml
> Install from source code to use the latest docs of TSDB and PyGrinder

- .github/workflows/testing_ci.yml
- requirements.txt
> Fixing dependency error in testing_CI workflow

- pypots/base.py
- pypots/classification/base.py
- pypots/classification/brits/model.py
- pypots/classification/grud/model.py
- pypots/classification/raindrop/model.py
- pypots/clustering/base.py
- pypots/clustering/crli/model.py
- pypots/clustering/vader/model.py
- pypots/forecasting/base.py
- pypots/forecasting/bttf/model.py
- pypots/imputation/base.py
- pypots/imputation/brits/model.py
- pypots/imputation/csdi/model.py
- pypots/imputation/gpvae/model.py
- pypots/imputation/locf/model.py
- pypots/imputation/mrnn/model.py
- pypots/imputation/saits/model.py
- pypots/imputation/saits/modules/core.py
- pypots/imputation/transformer/model.py
- pypots/imputation/usgan/model.py
- tests/clustering/crli.py
- tests/clustering/vader.py
- tests/imputation/saits.py
1. making SAITS return attention weights, fixing #178;
2. adding deprecation warning and updating docs;
> Make SAITS return attention weights in predict()

- .github/workflows/stale.yml
- README.md
- docs/index.rst
- docs/install.rst
1. fixing #243;
2. updating docs;
> Fixing the problem about staling issues

- pypots/utils/__init__.py
- pypots/utils/visual.py
add two visualisation functions in utils
Fixing # (issue)
> Adding visualization functions

- pypots/base.py
- pypots/data/saving.py
- pypots/data/saving/__init__.py
- pypots/data/saving/h5.py
- pypots/data/saving/pickle.py
- tests/data/saving.py
add pickle_dump() and pickle_load(), update save_dict_into_h5()
> Updating package `pypots.data.saving`

- pypots/base.py
- pypots/classification/raindrop/modules/core.py
- pypots/classification/raindrop/modules/submodules.py
- pypots/cli/tuning.py
- pypots/data/saving/__init__.py
- pypots/data/saving/h5.py
- pypots/imputation/brits/model.py
- pypots/imputation/gpvae/model.py
- pypots/imputation/gpvae/modules/core.py
- pypots/imputation/locf/model.py
- pypots/imputation/mrnn/model.py
- pypots/imputation/usgan/model.py
- pypots/utils/metrics/error.py
- tests/data/saving.py
- tests/forecasting/bttf.py
- tests/forecasting/config.py
- tests/imputation/brits.py
- tests/imputation/csdi.py
- tests/imputation/gpvae.py
- tests/imputation/locf.py
- tests/imputation/mrnn.py
- tests/imputation/saits.py
- tests/imputation/timesnet.py
- tests/imputation/transformer.py
- tests/imputation/usgan.py
1. fixing #276;
2. adding load_dict_from_h5();
3. adding options lazy_load and torch_n_threads for pypots-cli tuning;
4. checking the shapes of inputs in error calculation functions;
> Updating GP-VAE, adding load_dict_from_h5, etc.

- pypots/cli/tuning.py
- pypots/imputation/base.py
- pypots/imputation/mrnn/data.py
- pypots/imputation/mrnn/modules/core.py
- pypots/imputation/mrnn/modules/submodules.py
1. fixing #283 and speeding up MRNN;
2. updating the tuning functionality;
> Fix issues in MRNN and update the hyperparameter tuning functionality

- pypots/__init__.py
- pypots/data/saving/h5.py
Update load_dict_from_h5() to remove the yaml part.
> Updating load_dict_from_h5() 

- README.md
- docs/about_us.rst
- docs/conf.py
- docs/examples.rst
- docs/index.rst
> Update logo URLs

- .github/ISSUE_TEMPLATE/bug-report.yml
- pypots/classification/grud/data.py
- pypots/imputation/locf/__init__.py
- pypots/imputation/locf/model.py
- pypots/imputation/locf/modules/__init__.py
- pypots/imputation/locf/modules/core.py
1. fixing #306;
2. update issue config;
> Refactor LOCF implementations

- pypots/base.py
- pypots/imputation/__init__.py
- pypots/imputation/mean/__init__.py
- pypots/imputation/mean/model.py
- pypots/imputation/median/__init__.py
- pypots/imputation/median/model.py
- tests/imputation/mean.py
- tests/imputation/median.py
1. add Mean as a naive imputation method;
2. add Median as a naive imputation method;
> Add mean and median as imputation methods

- .github/workflows/testing_ci.yml
- .readthedocs.yaml
- docs/conf.py
- pypots/data/generating.py
- tests/classification/brits.py
- tests/classification/grud.py
- tests/classification/raindrop.py
- tests/clustering/crli.py
- tests/clustering/vader.py
- tests/global_test_config.py
- tests/imputation/autoformer.py
- tests/imputation/brits.py
- tests/imputation/crossformer.py
- tests/imputation/csdi.py
- tests/imputation/dlinear.py
- tests/imputation/etsformer.py
- tests/imputation/fedformer.py
- tests/imputation/gpvae.py
- tests/imputation/informer.py
- tests/imputation/locf.py
- tests/imputation/mean.py
- tests/imputation/median.py
- tests/imputation/mrnn.py
- tests/imputation/patchtst.py
- tests/imputation/saits.py
- tests/imputation/timesnet.py
- tests/imputation/transformer.py
- tests/imputation/usgan.py
1. fixing failed doc building. Fix sphinx version to 7.2.6, this is to avoid an error when sphinx upgrades to 7.3.6;
2. fixing a bug in gene_random_walk();
3. refactoring unit testing configs;
> Fix failed doc building, fix a bug in gene_random_walk(), and refactor unit testing configs

- docs/pypots.imputation.rst
- docs/references.bib
- pypots/imputation/__init__.py
- pypots/imputation/film/__init__.py
- pypots/imputation/film/core.py
- pypots/imputation/film/data.py
- pypots/imputation/film/model.py
- pypots/nn/modules/film/__init__.py
- pypots/nn/modules/film/backbone.py
- pypots/nn/modules/film/layers.py
- tests/imputation/film.py
> Implement FiLM as an imputation model

- .github/workflows/testing_ci.yml
- .github/workflows/testing_daily.yml
1. fix the error in https://github.com/WenjieDu/PyPOTS/actions/runs/8878263999/job/24373550637;
> Fix failed CI testing on macOS with Python 3.7

- pypots/imputation/__init__.py
- pypots/imputation/koopa/__init__.py
- pypots/imputation/koopa/core.py
- pypots/imputation/koopa/data.py
- pypots/imputation/koopa/model.py
- pypots/nn/modules/koopa/__init__.py
- pypots/nn/modules/koopa/backbone.py
- pypots/nn/modules/koopa/layers.py
- tests/imputation/koopa.py
> Add Koopa modules and implement it as an imputation model 

- pypots/imputation/__init__.py
- pypots/imputation/reformer/__init__.py
- pypots/imputation/reformer/core.py
- pypots/imputation/reformer/data.py
- pypots/imputation/reformer/model.py
- pypots/nn/modules/reformer/__init__.py
- pypots/nn/modules/reformer/autoencoder.py
- pypots/nn/modules/reformer/layers.py
- pypots/nn/modules/reformer/local_attention.py
- pypots/nn/modules/reformer/lsh_attention.py
- tests/imputation/reformer.py
> Add Reformer as an imputation model

- .github/workflows/testing_ci.yml
- README.md
- README_zh.md
- docs/install.rst
- setup.py
1. fix #435;
2. raise the minimum support python version to v3.8;
> Raise the minimum support python version to v3.8

- README.md
- README_zh.md
- docs/index.rst
- docs/milestones.rst
- docs/references.bib
- pypots/cli/tuning.py
- pypots/imputation/tide/__init__.py
- pypots/imputation/tide/model.py
- setup.py
> Use `inspect` to fetch models arguments and update docs

- README.md
- docs/index.rst
- pypots/classification/grud/data.py
1. fill in still-missing values of the empirical mean in GRUD with 0 to make it more robust with massive missing data;
2. update docs;
> Make classification GRUD more robust, and update docs

- docs/conf.py
> Update docs conf

- docs/conf.py
> Use xeLatex engine to avoid Unicode error

- .github/workflows/testing_ci.yml
- .github/workflows/testing_daily.yml
> Allow failure when PR gets merged before jobs get finished

- docs/examples.rst
Fixing #496 
This is fixing the mentioned issue with as minimal changes as possible, keeping the minimality of this example. But I've seen that in the notebook the imputaton example with saits has already been extended to newer releases from pypots and tsdb. 
If this is helpful, feel free to modify the PR such that it is useful for your quickstart example. :) I'm aware that maybe `load_specific_dataset` could be changed to use BenchPOTS or so, but as this would make the example less minimal for now I refrained from doing so yet...
Best,
> Doc update Quickstart Example

- .github/workflows/stale.yml
1. update the stale workflow to exempt PRs with specific labels;
> Update the stale workflow

- .github/workflows/testing_ci.yml
- tests/imputation/llms/__init__.py
- tests/imputation/llms/timellm.py
> Make pytest ignore LLM-based testing cases

- README.md
- README_zh.md
- docs/index.rst
- docs/pypots.imputation.rst
- docs/references.bib
- pypots/cli/tuning.py
- pypots/imputation/__init__.py
- pypots/imputation/gpt4ts/__init__.py
- pypots/imputation/gpt4ts/core.py
- pypots/imputation/gpt4ts/data.py
- pypots/imputation/gpt4ts/model.py
- pypots/nn/modules/gpt4ts/__init__.py
- pypots/nn/modules/gpt4ts/backbone.py
- tests/imputation/llms/gpt4ts.py
> Implement GPT4TS for time series imputation

- pypots/data/saving/pickle.py
> Load pickled data file with pd.read_pickle for pandas>=2

- pypots/base.py
- pypots/classification/base.py
- pypots/clustering/base.py
- pypots/forecasting/base.py
- pypots/forecasting/fits/core.py
- pypots/forecasting/gpt4ts/core.py
- pypots/forecasting/tefn/core.py
- pypots/forecasting/timellm/core.py
- pypots/forecasting/timemixer/core.py
- pypots/imputation/base.py
- pypots/imputation/timellm/model.py
1. fixing #619;
2. remove useless `X_pred` construction in forecasting models without decoder;
> Add attribute `amp_enabled` to switch `autocast`

- docs/install.rst
- pypots/version.py
- requirements/conda_env.yml
- requirements/requirements.txt
1. fixing #609 by bumping tsdb to v0.7.1;
2. releasing v0.12;
> Release v0.12 and bump TSDB to v0.7.1

- pypots/base.py
1. fixing #575, send model and data to the first item in the device list;
> Fix the bug data and mode not on same device

- pypots/base.py
- pypots/clustering/crli/model.py
- pypots/imputation/koopa/model.py
- pypots/imputation/usgan/model.py
> Fix failed CRLI, Koopa, and USGAN on multiple GPUs

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/ISSUE_TEMPLATE/model-addition.yml
- .github/ISSUE_TEMPLATE/other-issues.yml
- .github/workflows/greetings.yml
- tests/data/saving.py
- tests/global_test_config.py
1. updating testing configs and test-data saving path;
2. updating issue templates and greetings;
> Update testing configs and issue templates

- pypots/classification/base.py
- pypots/classification/brits/model.py
- pypots/classification/csai/model.py
- pypots/classification/grud/model.py
- pypots/classification/itransformer/model.py
- pypots/classification/raindrop/model.py
- pypots/classification/saits/model.py
- pypots/classification/tefn/model.py
- pypots/classification/timesnet/model.py
- pypots/classification/ts2vec/model.py
- tests/classification/brits.py
- tests/classification/csai.py
- tests/classification/grud.py
- tests/classification/itransformer.py
- tests/classification/raindrop.py
- tests/classification/saits.py
- tests/classification/tefn.py
- tests/classification/timesnet.py
- tests/classification/ts2vec.py
> Add `predict_proba()` for classification models

- pypots/base.py
- pypots/clustering/crli/model.py
- pypots/clustering/vader/model.py
- pypots/forecasting/gpt4ts/model.py
- pypots/forecasting/timellm/model.py
- pypots/imputation/gpt4ts/model.py
- pypots/imputation/timellm/model.py
- pypots/imputation/usgan/model.py
> Fix the bug that model state not a deep copy

- pypots/classification/tefn/core.py
- tests/classification/tefn.py
> Fix failed CLAS TEFN with `ROC AUC`<0.5

- pypots/anomaly_detection/__init__.py
- pypots/anomaly_detection/autoformer/__init__.py
- pypots/anomaly_detection/autoformer/model.py
- pypots/anomaly_detection/base.py
- requirements/conda_env.yml
- requirements/requirements.txt
- tests/anomaly_detection/__init__.py
- tests/anomaly_detection/autoformer.py
- tests/global_test_config.py
> Add ANOD Autoformer

- pypots/forecasting/bttf/model.py
- run_full_test.sh
- tests/forecasting/bttf.py
- tests/forecasting/timemixer.py
- tests/global_test_config.py
- tests/imputation/segrnn.py
> Fix OOM TimeLLM when testing

- .github/workflows/testing_ci.yml
- .github/workflows/testing_daily.yml
> Bump the least version of Python to 3.9 in GitHub CI workflow

- .gitignore
- README.md
- README_zh.md
- docs/index.rst
- docs/pypots.imputation.rst
- docs/pypots.nn.rst
- docs/references.bib
- pypots/imputation/__init__.py
- pypots/imputation/totem/__init__.py
- pypots/imputation/totem/core.py
- pypots/imputation/totem/model.py
- pypots/nn/modules/totem/__init__.py
- pypots/nn/modules/totem/autoencoder.py
- pypots/nn/modules/totem/layers.py
- tests/imputation/totem.py
> Add TOTEM modules and IMPU TOTEM

- requirements/conda_dev_env.yml
- requirements/requirements_dev.txt
Fixing https://github.com/WenjieDu/PyPOTS/issues/575#issuecomment-2778568973
> Update dependency versions for development environment

- pypots/nn/modules/timellm/backbone.py
> Fix AttributeError: 'NoneType' object has no attribute 'endswith' in TimeLLM

- .github/workflows/issue_manager.yml
> Add issue manger to auto close completed issues

- tests/global_test_config.py
> Decrease anomaly rate in CI testing to avoid GPT4TS outputting NaNs

- .github/workflows/issue_manager.yml
> Fix failed issue manager

- .github/workflows/greetings.yml
https://github.com/actions/first-interaction/issues/10#issuecomment-2201870495
1. fixing #726;
> Fix failed greeting workflow

- pypots/forecasting/__init__.py
- pypots/forecasting/dlinear/__init__.py
- pypots/forecasting/dlinear/core.py
- pypots/forecasting/dlinear/model.py
- tests/forecasting/dlinear.py
> Add forecasting DLinear

- pypots/forecasting/__init__.py
- pypots/forecasting/dlinear/__init__.py
- pypots/forecasting/dlinear/core.py
- pypots/forecasting/film/__init__.py
- pypots/forecasting/film/core.py
- pypots/forecasting/film/model.py
- pypots/forecasting/fits/core.py
- pypots/forecasting/micn/__init__.py
- pypots/forecasting/micn/core.py
- pypots/forecasting/moderntcn/core.py
- pypots/forecasting/moment/core.py
- pypots/forecasting/tefn/core.py
- pypots/forecasting/timemixer/core.py
- pypots/forecasting/timesnet/core.py
- tests/forecasting/film.py
> Add forecasting FiLM

- .github/workflows/greetings.yml
> Update configs in greetings
